# Copyright © 2025 Cai Yaoxing
# SPDX-License-Identifier: GPL-3.0-only
# This file is part of TheCalculater.
# See the file LICENSE in the project root or go to
# <https://www.gnu.org/licenses/gpl-3.0.html> for detailed license information.
name: Setup Conan
description: Setup Conan package manager

runs:
  using: 'composite'
  steps:
    - uses: conan-io/setup-conan@v1
      id: setup-conan
      
    - uses: actions/cache@v5
      id: conan-cache
      with:
        key: ${{ runner.os }}-conan-${{ hashFiles('cmake/conan_profiles/*.in', 'conanfile.py') }}-v1
        path: ${{ steps.setup-conan.outputs.conan-home }}/p
        restore-keys: |
          ${{ runner.os }}-conan-

    - uses: gacts/run-and-post-run@v1
      with:
        post: if [ "${{ steps.conan-cache.outputs.cache-hit }}" != "true" ]; then conan cache clean; fi
