# Copyright © 2025 Cai Yaoxing
# SPDX-License-Identifier: GPL-3.0-only
# This file is part of TheCalculater.
# See the file LICENSE in the project root or go to
# <https://www.gnu.org/licenses/gpl-3.0.html> for detailed license information.
name: CMake CI

on:
  push:
    branches-ignore: master
  pull_request:
    branches:
      - master
      - release/**
      - develop

jobs:
  build:
    if: |
      (github.event_name == 'push' && !contains(github.event.head_commit.message, '[WIP]')) ||
      (github.event_name == 'pull_request')
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [linux, macos, windows]
        include:
          - os: windows
            qt_arch: win64_mingw
            runner: windows-latest
          - os: linux
            qt_arch: linux_gcc_64
            runner: ubuntu-latest
          - os: macos
            qt_arch: clang_64
            runner: macos-latest

    env:
      CMAKE_VERSION: 4.3.1
      CMAKE_MINOR_VERSION: 4.3
      BUILD_TYPE: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup CMake
        uses: lukka/get-cmake@latest
        id: get-cmake
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Update Compiler
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            C:/msys64/usr/bin/pacman -Syu --noconfirm
            C:/msys64/usr/bin/pacman -S --noconfirm mingw-w64-x86_64-clang mingw-w64-x86_64-lld

            echo "C_COMPILER=C:/msys64/mingw64/bin/clang.exe" >> $GITHUB_ENV
            echo "CXX_COMPILER=C:/msys64/mingw64/bin/clang++.exe" >> $GITHUB_ENV
            sed -i "1i\C:/msys64/mingw64/bin" $GITHUB_PATH
          elif [ "${{ matrix.os }}" = "linux" ]; then
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y libstdc++-15-dev

            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 22 all
            sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-22 100
            sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-22 100
            sudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-22 100

            # You know what's the dumbest thing on earth?
            sudo sed -i '2011d' /usr/include/c++/15/bits/std.cc
            sudo sed -i '2012d' /usr/include/c++/15/bits/std.cc

            echo "C_COMPILER=/usr/bin/clang-22" >> $GITHUB_ENV
            echo "CXX_COMPILER=/usr/bin/clang++-22" >> $GITHUB_ENV
            echo "LDFLAGS=-L/usr/lib/llvm-22/lib" >> $GITHUB_ENV
          else
            brew update
            brew install llvm lld

            LLVM_PREFIX=$(brew --prefix llvm)

            echo "PATH=$LLVM_PREFIX/bin:$PATH" >> $GITHUB_ENV

            echo "CC=$LLVM_PREFIX/bin/clang" >> $GITHUB_ENV
            echo "CXX=$LLVM_PREFIX/bin/clang++" >> $GITHUB_ENV

            echo "LDFLAGS=-L$LLVM_PREFIX/lib/c++ -L$LLVM_PREFIX/lib/unwind -lunwind" >> $GITHUB_ENV
            echo "CPPFLAGS=-I$LLVM_PREFIX/include" >> $GITHUB_ENV

            echo "CMAKE_PREFIX_PATH=$LLVM_PREFIX" >> $GITHUB_ENV

            # Do you know how dumb it is?
            sed -i '' '3c\
            set(_clang_modules_json_impl "c++/libc++")
            ' ${{ steps.get-cmake.outputs.cmake-path }}/../share/cmake-${{ env.CMAKE_MINOR_VERSION }}/Modules/Compiler/Clang-CXX-CXXImportStd.cmake

            echo "C_COMPILER=$LLVM_PREFIX/bin/clang" >> $GITHUB_ENV
            echo "CXX_COMPILER=$LLVM_PREFIX/bin/clang++" >> $GITHUB_ENV
            sed -i '' '1i\
            $LLVM_PREFIX/bin' $GITHUB_PATH
          fi
        shell: bash

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true
        
      - name: Configure CMake 
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -G "Ninja" \
            -D CMAKE_C_COMPILER="$C_COMPILER" \
            -D CMAKE_CXX_COMPILER="$CXX_COMPILER" \
            -D THIRDPARTY_CLANG_EXECUTABLE="$C_COMPILER" \
            -D THIRDPARTY_CLANGXX_EXECUTABLE="$CXX_COMPILER" 
        shell: bash

      - name: Build project
        run: |
          cmake --build build --config ${{ env.BUILD_TYPE }}
        shell: bash

      - name: Run tests
        shell: bash
        run: |
          cd bin
          ./tests || true
          rm ./tests || true
          rm -rf log || true
          rm *.json5 || true
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TheCalculater-${{ matrix.os }}
          path: bin/
          retention-days: 2

      - name: Start tmate SSL debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ (failure() || contains(github.event.head_commit.message, '[forcedbg]')) && (contains(github.event.head_commit.message, format('[dbg{0}]', matrix.os))) }}