name: CMake CI

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
    branches:
      - master
      - release/**
      - develop

jobs:
  build:
    if: |
      (github.event_name == 'push' && !contains(github.event.head_commit.message, '[WIP]')) ||
      (github.event_name == 'pull_request')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug, Release]
        include:
          - os: windows-latest
            generator: "MinGW Makefiles"
            mingw_url: https://github.com/niXman/mingw-builds-binaries/releases/download/14.2.0-rt_v12-rev2/x86_64-14.2.0-release-posix-seh-msvcrt-rt_v12-rev2.7z
            qt_arch: win64_mingw
            toolset: mingw
          - os: ubuntu-latest
            generator: "Unix Makefiles"
            qt_arch: linux_gcc_64
            toolset: gcc
          - os: macos-latest
            generator: "Unix Makefiles"
            qt_arch: clang_64
            toolset: clang

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore MinGW
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v4
        id: mingw-cache
        with:
          path: C:\msvcrt-mingw
          key: mingw-mingw-14.2.0-rt_v12-rev2-fixed  # 直接哈希URL作为唯一标识
          restore-keys: mingw-
          mode: restore-only
      - name: Install MinGW
        if: matrix.os == 'windows-latest' && steps.mingw-cache.outputs.cache-hit != 'true'
        run: |
          curl -L -o mingw.7z "${{ matrix.mingw_url }}"
          7z x -y mingw.7z -o"C:\msvcrt-mingw" > nul
          rm mingw.7z
        shell: bash
      - name: Save MinGW
        if: matrix.os == 'windows-latest' && steps.mingw-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: C:\msvcrt-mingw
          key: mingw-mingw-14.2.0-rt_v12-rev2-fixed
          mode: save-only
      - name: Add mingw to PATH
        if: matrix.os == 'windows-latest'
        run: echo "C:/msvcrt-mingw/mingw64/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          arch: ${{ matrix.qt_arch }}
          cache: true

      # 统一配置步骤
      - name: Configure CMake
        run: |
          # export BOOST_ROOT=

          cmake -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_PREFIX_PATH="${{ steps.install-qt.outputs.qt-path }}" \
            -G "${{ matrix.generator }}"
        shell: bash

      - name: Build project
        run: |
          cmake --build build --config ${{ matrix.build_type }}

      - name: Run tests
        run: |
          cd build
          ctest -C ${{ matrix.build_type }} --output-on-failure